### ISSUE TITLE
Implement caching strategy for data and result sets

### ISSUE THREAD

**Issue by bruth** [chop-dbhi/avocado#109]
Most use cases thus far for Avocado (and Harvest in general) has dealt with incremental and/or planned data refreshes. This provides a great environment for hefty caching of the data and any derived statistics such as counts, averages, etc.

In addition, the `Data(Context|View|Query)` models provide an interface for generating result sets that are typically used multiple times (either within or across sessions). Like the data, each result set has a small set of statistics that are computed (e.g. count). These data are much more volatile since any change to the underlying query will invalidate the cache.

Here are the primary areas where caching should be implemented:

**DataField**
- [x] distinct values for discrete/enumerable data types
  - Free-text search can be applied in the application using Python's regular expressions
- [x] distribution data including clustering and outliers for continuous data
- [x] aggregate statistics, e.g. count, avg, std dev, min, max

**DataContext**
- [x] distinct count of the _root_ objects (e.g. Patient)

**DataQuery**
- [x] result count of the applied context and view
- [ ] _sliding window_ cache of the pre-formatted result set
  - the frame size can be a setting which should be configured depending on how much RAM is available and the expected concurrent users (so active cache does not get stomped on)

The implementation should use Django's [cache APIs](https://docs.djangoproject.com/en/1.5/topics/cache/) to keep things simple. A common strategy for cache invalidation is to increment a version number or update the datetime (in seconds) on the cache key which is then stored somewhere. Old cache will eventually be culled since it is no longer being accessed (at least when using memcache which is the only atomic (and reliable) cache backend Django supports). This is in favor of explicitly removing it since that requires an additional operation.

`DataField` instances could contain a `data_version` that is updated any time the underlying data changes for that column. This key will be the _variable_ when generating the cache key. The key _template_ would be something like `avocado:field:<pk>:<data_version>:<type>`. This would produce keys such as:
- `avocado:field:4:10:values`
- `avocado:field:4:10:dist`
- `avocado:field:4:10:stats`
- etc.

**Comment by murphyke** [comment]
I don't know what the plans are exactly for caching result sets, but it seems that dynamic entities such as results might easily fill up the cache (or the cache item slots) and evict the basic field caches, which are too precious to lose.  Maybe Avocado could support multiple cache backends, so installations could have different caches for different purposes.  AVOCADO_FIELD_CACHE and AVOCADO_DYNAMIC_CACHE settings could refer to different cache backend aliases.  Even currently, if a user wants to use default Django view caching, those cached views could wind up pushing the Avocado cache items out of the default cache -- is that correct?

**Comment by bruth** [comment]
@murphyke That is a good idea and it's backward compatible. As you stated, there is static cache, controlled by the system or developer, and a dynamic cache which is driven by users. To prevent confusion, it may be wise to call them something explicit like `AVOCADO_DATA_CACHE` and `AVOCADO_QUERY_CACHE`.
