### ISSUE TITLE
Add support for Django 1.6

### ISSUE THREAD

**Issue by bruth** [chop-dbhi/avocado#153]
Depends on cbmi/modeltree#11

**Comment by sgithens** [comment]
I've been starting to dig in to this, and from browsing and grepping Avocado,  I haven't quite pinned down yet where we actually add things/models/fields to Haystack (I'm guessing there is a fancy metadata driven way...)

However, I did open up the whoosh.index that was left over after running tests in ipython, and wanted to float the idea that maybe an api change somewhere has caused us to now be searching *both* the datafield and dataconcept indexes.  

For instance, the failing test:
```
tests/cases/search/tests.py:
82-ish        self.assertEqual(len(search('Erick')), 1)
failing with 2,1
```

In the whoosh index there is:
```
{u'django_ct': u'avocado.datafield',
  u'django_id': u'5',
  u'id': u'avocado.datafield.5',
  'text': u'First Name\nFirst Names\n\n\nemployee\nAvocado\n\n\n\nHarvest\n\n\n\n\nAaron\nEric\nErick\nErin\nMel\nZac\n\n',
  'text_auto': u'First Name\nFirst Names\n\n\nemployee\nAvocado\n\n\n\nHarvest\n\n\n\n\nAaron\nEric\nErick\nErin\nMel\nZac\n\n\n'},
[snip]
{u'django_ct': u'avocado.dataconcept',
  u'django_id': u'5',
  u'id': u'avocado.dataconcept.5',
  'text': u'First Name\nFirst Names\n\n\nAvocado\n\n\n\nHarvest\n\n\n\n\n\nFirst NameFirst Name\nFirst Names\n\n\nemployee\nAvocado\n\n\n\nHarvest\n\n\n\n\nAaron\nEric\nErick\nErin\nMel\nZac\n\n\n\n',
  'text_auto': u'First Name\nFirst Names\n\n\nAvocado\n\n\n\nHarvest\n\n\n\n\n\nFirst NameFirst Name\nFirst Names\n\n\nemployee\nAvocado\n\n\n\nHarvest\n\n\n\n\nAaron\nEric\nErick\nErin\nMel\nZac\n\n\n\n\n'},
```

Maybe a labeling change or something is causing it to search (or index) text on both the data Field and Concept:

```
from whoosh.index import open_dir
ix = open_dir('./tests/whoosh.index')
docs = list(ix.searcher().documents())
from whoosh.qparser import QueryParser
qp = QueryParser("text", schema=ix.schema)
q = qp.parse("Erick")
s.search(q)
list(s.search(q))

51: <Top 2 Results for Term('text', u'erick') runtime=0.00948882102966>,
 52: [<Hit {u'django_ct': u'avocado.datafield', 'text': u'First Name\nFirst Names\n\n\nemployee\nAvocado\n\n\n\nHarvest\n\n\n\n\nAaron\nEric\nErick\nErin\nMel\nZac\n\n', u'django_id': u'5', 'text_auto': u'First Name\nFirst Names\n\n\nemployee\nAvocado\n\n\n\nHarvest\n\n\n\n\nAaron\nEric\nErick\nErin\nMel\nZac\n\n\n', u'id': u'avocado.datafield.5'}>,
  <Hit {u'django_ct': u'avocado.dataconcept', 'text': u'First Name\nFirst Names\n\n\nAvocado\n\n\n\nHarvest\n\n\n\n\n\nFirst NameFirst Name\nFirst Names\n\n\nemployee\nAvocado\n\n\n\nHarvest\n\n\n\n\nAaron\nEric\nErick\nErin\nMel\nZac\n\n\n\n', u'django_id': u'5', 'text_auto': u'First Name\nFirst Names\n\n\nAvocado\n\n\n\nHarvest\n\n\n\n\n\nFirst NameFirst Name\nFirst Names\n\n\nemployee\nAvocado\n\n\n\nHarvest\n\n\n\n\nAaron\nEric\nErick\nErin\nMel\nZac\n\n\n\n\n', u'id': u'avocado.dataconcept.5'}>]}
```

Will poke at it more tomorrow.

**Comment by sgithens** [comment]
Or maybe it's only searching only one of DataField and DataConcept, but is for some reason searching text and the autocomplete index text_auto

**Comment by murphyke** [comment]
Hi Steve, my understanding is that the Haystack-prescribed file https://github.com/chop-dbhi/avocado/blob/master/avocado/search_indexes.py and the templates in https://github.com/chop-dbhi/avocado/tree/master/avocado/templates/search/indexes/avocado determine what gets indexed. Fields and concepts are both indexed.  In typical cases this results in a lot of redundancy, but the idea is that if the search term matches anywhere in a concept or its underlying fields (or the category to which it belongs), the concept will match.  So searching for 'length' would match a Dimensions concept that consisted of Length, Height, and Depth fields.

**Comment by sgithens** [comment]
Thanks Kevin!  I missed the document templating part when skimming the haystack docs.

So, I went in to the dataconcept_text.txt, and removed the bit that actually inserts the values.  And while it caused some other concept tests to fail, the DataField.objects.search error I was starting with does now seem to pass, so it might indeed have something to do with the index for both concepts and fields getting sucked in to a search for only one of them.

**Comment by sgithens** [comment]
Just as a sanity check, in all the erroring tests, I switched the len to look at a list()'d set of the items instead of the result from the querysets count, and they all passed.  So it seems safe to say the issue is with the counting, since iterating through them returns the correct number of items.

https://gist.github.com/sgithens/538c5180dd4080fc2635

Not sure if this is correctly fixable somewhere, or if we'll need to expand on the monkey patching.  I should probably also try running the unit tests for haystack with the whoosh backend.

**Comment by bruth** [comment]
@sgithens Thank you for digging into this. Fortunately we control the output the [`search` method](https://github.com/chop-dbhi/avocado/blob/master/avocado/managers.py#L37-L43). The Haystack query class implements [`__len__` differently from `__iter__`](https://github.com/toastdriven/django-haystack/blob/master/haystack/query.py#L89-L105), so it is certainly possible the computed count vs. the actual count could differ.

**Comment by bruth** [comment]
I ran the tests against the Elasticsearch backend.. and no duplicates showed! So there is definitely something funny going on with Whoosh. There is a [Whoosh issue](https://bitbucket.org/mchaput/whoosh/issue/97/search-index-contains-a-lot-of-duplicates) that describes this behavior, but nothing was resolved because noone provided a reproducible case just using Whoosh.

**Comment by bruth** [comment]
I updated to Haystack to 2.3.1 and Whoosh to 1.6 with no luck. However, I ran the tests with the Solr backend and the tests passed. At this point I am quite confident the issue is Whoosh.

**Comment by sgithens** [comment]
That's great.  What do you feel would be the best way forward as far as getting Django 1.6 supported?  Do you think it would be ok to say that currently there is an issue with Whoosh as a backend, or is that a must have as an officially supported harvest haystack backend?

Also, +1 to the above comment about dropping Django 1.4 support ( unless there is a known community member actively running and invested in it)
