### ISSUE TITLE
Support for job queue and background execution of queries

### ISSUE THREAD

**Issue by bruth** [chop-dbhi/avocado#231]
The scale of some Harvest applications have reached the point that queries are taking longer than what is appropriate to classify as "real-time adhoc queries". This is still the target use case, however some applications do not necessarily require the _real-time_ aspect, but still want the power of the query generation.

The current pipeline of query execution does not take in consideration long-running queries and therefore is naively executed in the main thread of the program which blocks until results are returned. This is problematic for two reasons:
- No other operations can be performed in the main thread
- The only method for canceling the query is signaling an interrupt (Ctrl+C) on the process (assuming an interactive session) or terminating the process by an external means

This puts the state of the application and database in a potentially unknown/broken state which ultimately impacts the user. A common response to canceling the query is to _try it again_ which could compound the issue if the previous query was not canceled at the database level.

The high-level approach is to:
- Introduce the notion of a "job" that corresponds to some external processing such as a database query, analysis pipeline, etc.
- Focus on user-defined query jobs first since they are the current issue since they are much more difficult to predict (due to their arbitrary nature)
- Define various states which can be used to report on the state of the query by the main
  - e.g. `queued`, `starting`, `running`, `finished`, `canceled`, `error`, `expired`
- Add mechanisms for spawning a thread or process that will dequeue and handle the lifecycle of the job (updating state as it's being processed)
- Provide a API for accessing a job and getting it's state

Technical considerations:
- The job API must supporting canceling/killing the job
  - This would terminate the thread/process, but also propagate to external systems such as canceling a database query
  - This prevents the _stampeding effect_ and keeps the systems clean of rogue state
- The output of the job (i.e. results from the database) must be stored somewhere
  - The data is no longer being produced/streamed into the main thread and therefore is not accessible. Possible solutions include using:
    - Shared data structures between threads
    - Cross-process communication
    - External system for temporary storage (this feels safest and most flexible for future growth)
  - All data must have an expiration so the interim storage does not balloon
- Any performance loss of this process should not be noticeable to typical Harvest projects
  - Ideally this would be the _only_ pipeline, however if needed there could be an _expedited_ path which skips the queue and executes it immediately
- Although it theoretically makes sense to implement in Python, it may not need to be if the abstraction is well defined

**Comment by tjrivera** [comment]
I'm going to attempt some sort of implementation of HTQ into the Harvest stack with the CBTTC Harvest application as a model.

**Comment by bruth** [comment]
I am working on the query canceling part: https://github.com/chop-dbhi/avocado/issues/280

**Comment by bruth** [comment]
I just made an observation that canceling an export after the formatter processing has begun does not stop the processing. This is another reason why queries needs to be executed in a separate thread or process so they can be managed.

**Comment by bruth** [comment]
It has been many months since the original inception and description of this issue, so I want to clarity and restate the intent of this issue.

The outcome of this feature is to provide more control over queries being executed and the results they produce. *Control* is defined conceptually as:

- Visibility of the queries currently running
- Management over when queries execute to control either system resources or throttle resources per user
- Some notion of persistence of a query and its results for later reference

The motivation for this feature is the ability for users to execute a query and access the results at a later time. In Cilantro, this could be implemented in two contexts:

- Rather than clicking "View Results" which would immediately execute the query, one could (hypothetically) click "Run For Later"
- The user clicks "View Results", but realizes or is told (#296) the query may take a while and wants to "background" the query so they can move on

In either case, the requirements are the same:

- A means of persisting a "planned" query and keeping track of it's state
- Storing the results of query that can be reference at a later time

We have persistent queries in the form of a saved `DataQuery` tied to a user. This may or may not be appropriate for this feature, but it's a starting point for thinking about what may need to be added to the API.

The current thought for storing the results is to simply cache them (#109) using the current cache APIs. This is likely to be good enough until there is more evidence of how this feature is being used.

With these base features already in place, this issue is distilled down to **keeping tracking of all planned, running, and cached ad-hoc queries.** The API should support:

- [ ] Retrieving a list of ad-hoc queries
- [ ] Accessing the query results if the cache is still present
- [ ] Hooking into the [query cancellation facilities](https://github.com/chop-dbhi/avocado/blob/master/avocado/query/utils.py)

Another way to think about it is that a administrative page of the running queries and their properties can be displayed with the ability to click through to the results or cancel it if it's running.
