### ISSUE TITLE
Question about custom QueryProcessor coercing an empty queryset

### ISSUE THREAD

**Issue by murphyke** [chop-dbhi/avocado#279]
If I want to return an empty queryset from a QueryProcessor, I've noticed that I can't just get the default queryset from the superclass and then return queryset.none().  Is the best/recommended way just to create a real context that won't match anything and build a queryset from that, e.g.:

    def empty_queryset():
        empty_spec = {'field': 'core.person.blinded_id', 'operator': 'in',
                      'value': ['impossible']}
        qs = DataContext(empty_spec).apply()
        return DataView().apply(qs)

**Comment by bruth** [comment]
> I've noticed that I can't just get the default queryset from the superclass and then return queryset.none()

Why not?

**Comment by murphyke** [comment]
Seemingly, returning `queryset.none()` has the same effect as just returning `queryset`.  This is not a high-priority issue, but maybe it's interesting.  Random aside: I notice that current Django's implementation of none() is different than 1.5's; I'm not sure when it changed or if it's relevant. I don't have time to look at this more right now.

**Comment by bruth** [comment]
@murphyke I added a test in PR #301 to address this issue for 2.4.x.
