### ISSUE TITLE
Add tools for tracking and canceling a query

### ISSUE THREAD

**Issue by bruth** [chop-dbhi/avocado#280]
Two functions that are database dependent:

- Function that takes a connection and gets the process ID for a query that is running.
- Function that takes the ID and cancels the query

**Comment by murphyke** [comment]
Re: future Oracle support, the standard Python Oracle driver seems to be cx_Oracle, which has a `cancel` extension method in its connection class.  This "[cancels a long-running transaction](http://cx-oracle.readthedocs.org/en/latest/connection.html?highlight=cancel#Connection.cancel)".

**Comment by bruth** [comment]
@murphyke Thanks. Should be easy enough to add.
