### ISSUE TITLE
Error when attempting to cancel a database query with a non-privileged user

### ISSUE THREAD

**Issue by bruth** [chop-dbhi/avocado#307]

**Comment by aaron0browne** [comment]
This is odd because it appears a user should be able to cancel backends initiated by the same user, which should cover all the harvest cases, right?

http://www.postgresql.org/docs/9.3/static/functions-admin.html#FUNCTIONS-ADMIN-SIGNAL-TABLE

**Comment by bruth** [comment]
What I discovered is that this error returns when the query is no longer running as well. Rather than just returned null or something it throws this error. Odd.
