### ISSUE TITLE
Exporting to CSV sometimes results in misaligned headers and values

### ISSUE THREAD

**Issue by ihodes** [chop-dbhi/avocado#317]
My basic setup is as follows: I have a table of patients, and I have many tables of toxicity measurements with schema like patient_id, value, scale, date. I have a data field for each of value, scale, and data. On top of that I have a DataConcept for each toxicity table, e.g. Hematuria, which has a custom formatter for HTML.

Sometimes (I haven't figured out how to reproduce this yet, but multiple people including me have seen this behavior) when exporting to CSV the column names do not match up with the column values. E.g. the header may say "scale, value, data", but the values may be "date, value, scale". 

I'll try to reproduce this and will update if/when I'm able!

**Comment by bruth** [comment]
Thanks for the report @ihodes. We've seen this behavior before if a concept is defined with multiple fields that do not have explicit ordering. Here is an example of a multi-field concept with explicit ordering.

![screen shot 2015-06-06 at 7 04 58 am](https://cloud.githubusercontent.com/assets/515142/8019406/6209c9c2-0c1a-11e5-8449-0c25ba959eec.png)

If the ordering is undefined, the order of the fields may be different from the order of the columns in the `select` query to retrieve the data.

**Comment by ihodes** [comment]
Aha, I'll do that, then. Thanks for the reply!
