### ISSUE TITLE
Document what `published` and `archived` means

### ISSUE THREAD

**Issue by bruth** [chop-dbhi/avocado#44]
Code of interest is here:
- https://github.com/cbmi/avocado/blob/2.x/avocado/core/models.py
- https://github.com/cbmi/avocado/blob/2.x/avocado/core/managers.py

**Comment by bruth** [comment]
@murphyke @tjrivera @aaron0browne Are any of you using these fields?

**Comment by aaron0browne** [comment]
I make use of the published flag, but haven't used the archived flag. Is my conception of intended object lifecycle as laid out below correct?

1. draft object: published = False, archived = False
2. object available for end users: published = True, archived = False
3. object deprecated: published = False, archived = True

**Comment by bruth** [comment]
@aaron0browne Thanks and yes that was the intended lifecycle. I expect `published` to be used since it is required to be set to be visible, but I was unsure if it actually mattered in practice. Specifically, however unpublished (non-archived) fields do you have? Are they kept around because you didn't delete them or are they eventually going to be published? How many fields do you have archived? This may be a better for @murphyke with PCGC being the second longest running Harvest application.

**Comment by tjrivera** [comment]
@bruth We use unpublished fields in CBTTC when we, as superusers, bring in some identifier that would never see be seen in production -- As a QA check. The lifecycle described by @aaron0browne matches my intended usage (though in practice archived is almost never used). I believe that avocado metadata migrations capture the "history" of a field and its usage in practice.

**Comment by murphyke** [comment]
@bruth We're not currently using archived concepts.  We have only briefly used archived concepts, when changing or decommissioning concepts that were used in saved queries.  That's a tricky scenario that is going to be difficult no matter what.  It would probably just as good to send out a deprecation notice to users with affected saved queries.  At one point I thought we might use a behind-the-scenes archived concept in our query processor (i.e. for a concept that we didn't want to expose to the user), but we wound up not doing that.

**Comment by bruth** [comment]
Thanks @tjrivera and @murphyke. I wanted confirm the lifecycle makes sense. Documentation on how and when to use the two fields to exercise the lifecycle is definitely needed.
